name: Python Audit

on:
  workflow_dispatch:
  schedule:
  - cron: '0 0 * * 1'

jobs:
  build_appimage:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out source
        uses: actions/checkout@v3
      - name: Run Audit
        uses: pypa/gh-action-pip-audit@v1.0.5
        with:
          inputs: |
            contrib/deterministic-build/requirements-binaries.txt
            contrib/deterministic-build/requirements-build-wine.txt
            contrib/deterministic-build/requirements-hw.txt
            contrib/deterministic-build/requirements-pip.txt
            contrib/deterministic-build/requirements-web3.txt
            contrib/deterministic-build/requirements.txt